/home/viperzer0/music/harmony_of_heroes-2014-full_album/09_baffle_ball.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/10_a_vivid_cruise_to_the_finish.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/13_rhythm_of_the_kong.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/22_cucco_revenge_squad.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/28_dark_horizons.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/40_king_dedednb.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/42_defending_corneria.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/49_johto_battlemix.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/71_m.o.t.h.e.r.f.u.o_o.e.r_.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/92_smashin_through_.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/93_smash_superstars.mp3
/home/viperzer0/music/harmony_of_heroes-2014-full_album/96_live_and_let_polygon.mp3
/home/viperzer0/music/harmony_of_heroes_final_smash/12_to_the_stars.mp3
/home/viperzer0/music/harmony_of_heroes_final_smash/16_hammered_bros..mp3
/home/viperzer0/music/harmony_of_heroes_final_smash/22_the_journey_to_castle_lololo.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/03-michael-schiciano-morning-glow.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/16-hatvgm-swinging-in-the-sewers.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/20-jordan-chin-tiago-rodrigues-boss-battle-1.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/21-lauren-the-flute-sealed-door.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/25-zach-kohlmeier-wayfarer.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/36-akihiro-akane-magus-the-mystic.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/37-jeremy-harris-jones-the-mountain-sings.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/38-dean-nguyen-matheus-manente-rhythm-of-earth-wind-sky.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/44-materia-brasilis-quinta-feira.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/46-string-player-gamer-gatos-symphony.mp3
/home/viperzer0/music/materia-collective/epoch-a-tribute-to-chrono-trigger/51-jared-collins-zeal-palace.mp3
