#!/bin/bash
killall -9 wpa_supplicant

rm -f /tmp/current_wpa.conf
wpa_passphrase "$1" > /tmp/current_wpa.conf 
wpa_supplicant -i wlp2s0 -D wext -c /tmp/current_wpa.conf -B

ifconfig enp12s0 down
ifconfig wlp2s0 down
dhclient -r wlp2s0 
iwconfig wlp2s0 essid "$1"
iwconfig wlp2s0 mode Managed
ifconfig wlp2s0 up
dhclient wlp2s0
