#!/bin/bash
# Silly little script to check if you're conencted to the internet!
result=$(ping -c 1 -W 4 google.com 2>&1 1>/dev/null) 
if [ -z "$result" ]; then
echo "I am connected! :D"
else
echo "I'm all alone ;n;"
fi

